### ISSUE TITLE
The README should feature yaml source code for a github action

### ISSUE THREAD

**Issue by pgrange** [pgrange/bash_unit#120]
Extracted from @iambumblehead https://github.com/pgrange/bash_unit/pull/117#issuecomment-1998328342:

The README should feature yaml source code for a github action and probably should link the project's own unit-test [action yaml file here.](https://github.com/pgrange/bash_unit/blob/master/.github/workflows/bash_unit.yml) For my own brief investigation one of the main concerns I had while comparing tools was "How could I setup a github action to uses this tool?" and if it looked maybe-difficult to me I moved on and looked for another tool. A strength of bash_unit is that it is easy to setup a unit-test pipeline on github that uses it. I feel less strongly about this last part of the suggestion: yaml source examples for both gitlab and github should be featured in collapsible sections at the README.

bash_unit.yml

```
name: test bash_unit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Unit testing with bash_unit
      run: |
        bash <(curl -s https://raw.githubusercontent.com/pgrange/bash_unit/master/install.sh)
        FORCE_COLOR=true ./bash_unit test/test*
```
